name: bpm

instance_groups:
- name: bpm
  azs: [z1,z2,z3]
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: test-server
    release: bpm
  vm_type: default
  stemcell: default
  networks:
  - name: default

releases:
- name: bpm
  version: latest

update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
