required = [
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/maxbrunsfeld/counterfeiter"
]

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/bytefmt"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/clock"

[[constraint]]
  name = "code.cloudfoundry.org/lager"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kr/pty"
  version = "1.1.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  version = "1.0.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
